config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'developers#index'
  get "developers", to: "developers#index", as: :developers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/communication_ability.rb
class CommunicationAbility < ApplicationRecord
  belongs_to :developer
  belongs_to :language
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :developer_abilities
  has_many :programming_languages, through: :developer_abilities

  has_many :communication_abilities
  has_many :languages, through: :communication_abilities
end

app/models/developer_ability.rb
class DeveloperAbility < ApplicationRecord
  belongs_to :developer
  belongs_to :programming_language
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :communication_abilities
  has_many :developers, through: :communication_abilities
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :developer_abilities
  has_many :developers, through: :developer_abilities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index

    @developers = Developer.all

    pl_term = params[:pl_term]
    cl_term = params[:cl_term]

    if (pl_term.present?)
      pl_term = pl_term.downcase
      @search_header = "Developers - " + [cl_term, pl_term].reject(&:blank?).join(", ")

      @developers = @developers.joins(:programming_languages, :languages)
        .where("programming_languages.name = ? ", pl_term)

      if (cl_term.present?)
        cl_term = cl_term.downcase
        @developers = @developers.joins(:languages)
          .where("languages.code = ?", cl_term)
      end

    else
      @search_header = "Developers - All"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/developers/index.html.erb
<div class="container">

  <div class="row">
    <div class="col">
      <h1 class="display-1">Developers</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= form_tag(developers_path, {method: :get, class: "form-group"}) do %>

        <div class="form-group">
          <%= label_tag 'Programming Language', nil, class: 'small_label' %>
          <%= text_field_tag :pl_term, params[:pl_term], class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag 'Communication Language', nil, class: 'small_label' %>
          <%= text_field_tag :cl_term, params[:cl_term], class: "form-control" %>
        </div>

        <%= submit_tag 'Search', class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-7">
      <h1 class="h1"><%= @search_header%></h1>
    </div>
    <div class="col">
      <h1 class="h5 float-right counter"><%= @developers.count%> Developers</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Programming Languages</th>
            <th scope="col">Languages</th>
          </tr>
        </thead>
        <tbody>
          <% @developers.each do |developer| %>
            <tr>
              <td><%= developer.id %></td>
              <td><%= developer.email %></td>
              <td><%= developer.programming_languages.map(&:name).join(", ").titleize %></td>
              <td><%= developer.languages.map(&:code).join(", ")  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>